add backend API to change user info
raihanizar/thread-center pull request #20
Opened 2024-03-16 10:35 UTC by ahmadbbaihaqi

add backend API to change user info username or password and little U…

2024-03-16 14:02 UTC, raihanizar requested changes
**src/app/api/v1/users/[id]/route.js**
- berdasarkan kode ini, URL parameternya gak kepake, ku bisa ngisi `user_id` nya ngasal (`PATCH /users/123456`), asal ada emailnya di body, usernya bisa keganti, tapi jadi kurang pas, untuk apa ada `user_id` kalo gak dipake
- saran perbaikan: accept `user_id` dalam endpoint, body-nya tapi hanya yg akan diganti saja (`newUsername` dan `newPassword`)
- cara accept parameter dyamic routes bisa liat contoh endpoint `GET /threads/{thread_id}`

2024-03-17 04:31 UTC, raihanizar requested changes
**src/app/api/v1/users/[id]/route.js** *(line 96)*
- responsenya udah benar, tapi payload utk bikin JWT jangan diganti, tetep dipakai `id` nya, sama spt login, gak pake `id` hanya ketika memberikan response

2024-03-20 06:18 UTC, raihanizar requested changes
kena error component not found di `./src/app/dashboard/new/page.js`, soalnya `CreateThreads.jsx` dihapus

paling `CreateThreads.jsx` nya kembalikan lagi aja, tapi isinya sesuai sama yg terbaru

cc: @ahmadbbaihaqi

2024-03-20 08:05 UTC, ahmadbbaihaqi commented
Done mas @raihanizar . Kalo dibalikin bentrok sama lain ga ya mas? Create Thread yg udahh d beresin

2024-03-20 08:09 UTC, ahmadbbaihaqi commented
saya upload ulang aja kali ya mas @raihanizar di branch baru. yg ini ditutup aja

2024-03-20 08:16 UTC, raihanizar requested changes
> saya upload ulang aja kali ya mas @raihanizar di branch baru. yg ini ditutup aja

`CreateThread.jsx` nya diisi file versi terbaru aja, biar gak bentrok sama yg di branch main, sekarang ku check beda soalnya

cc @ahmadbbaihaqi

2024-03-20 12:07 UTC, closed without merging