AUTH FEAT: create API for login and register plus little UI.
raihanizar/thread-center pull request #4
Opened 2024-03-13 10:03 UTC by ahmadbbaihaqi

Add some library to test this backend. add middleware to protect other page. add model schema for user and thread based on ERD

2024-03-13 14:58 UTC, raihanizar requested changes
**package.json**
- package `next` kehapus, tidak ada Next.js tanpa package `next` wkwk

**prisma/schema.prisma**
- model User ada firstName dan lastName, sedangkan di ERD tidak ada, tolong disesuaikan

**src/app/api/v1/auth/login/route.js**
- Maksud response sudah betul, tapi tolong samakan bentuk response (code & message) dengan api contract yg sudah kita buat.
- Nanti kirimkan JWT_SECRET yg digunakan

**src/app/api/v1/auth/register/route.js**
- Maksud response sudah betul, tapi tolong samakan bentuk response (code & message) dengan api contract yg sudah kita buat.
- Register tidak menerima firstName dan lastName, sesuaikan dengan API contract

2024-03-13 15:00 UTC, raihanizar requested changes
**package.json**
- kayaknya salah resolve conflict, yg sudah ada malah kehapus, 
- kita gak pakai s3 client, karena gak simpan gambar

2024-03-13 23:27 UTC, raihanizar requested changes
overall API nya udah jalan dan datanya masuk database, cuma ada beberapa catatan sebelum di-accept

**src/app/api/v1/auth/register/route.js**
- API masih accept firstName, lastName, coba dihilangkan
- skema data response successful belum sesuai dengan API contract: cukup output pesan berhasil aja, jangan semua data apalagi ada password di situ
- catch sebaiknya jangan diberi pesan "email already exist", karena catch buat error general, sedangkan di code ini belum ada logic ngecek email exist / nggak

**src/app/api/v1/auth/register/login.js**
- skema data response successful belum sesuai dengan API contract: atribut `data` coba diganti `payload`, `token` belum ada di dalam response

**src/components/auth/Register.jsx**
- Masih ada input first name last name
- Setelah register, coba bikin redirect ke halaman login

**src/components/auth/Login.jsx**
- Setelah login, coba bikin redirect ke halaman dashboard

2024-03-14 04:54 UTC, ahmadbbaihaqi commented
mohon maaf mas tidak teliti, re check ya mas @raihanizar

2024-03-14 15:27 UTC, closed without merging